### ISSUE TITLE
[Bug]: User OG image cannot render markdown

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1013]
### What happened?

I guess we need to just render static text vs pull the beginning of the users bio. Its probably better that way because someone could put inappropriate text in their bio before we catch it

Design could be modified as well

<img width="477" alt="CleanShot 2023-10-31 at 07 55 45@2x" src="https://github.com/typehero/typehero/assets/3660667/849f7585-4c7e-4829-8b59-b88c3beb4701">

- [ ] remove markdown for static text

**Comment by Dun-sin** [comment]
@bautistaaa can I work on this? and quick question how do you check for inappropriate text in the bio?

this is what i understand the issue says to do and questions:
- if the text is start with nothing related to markdown in it, it should be displayed normally without using markdown to render
- twitter OG image should be fixed on twitter, i don't understand this one, can you expand on the task here, because the issue title says image can't render markdown.
- you also want the design to be modified but where is that change needed

**Comment by bautistaaa** [comment]
> @bautistaaa can I work on this? and quick question how do you check for inappropriate text in the bio?
> 
> this is what i understand the issue says to do and questions:
> 
> * if the text is start with nothing related to markdown in it, it should be displayed normally without using markdown to render
> * twitter OG image should be fixed on twitter, i don't understand this one, can you expand on the task here, because the issue title says image can't render markdown.
> * you also want the design to be modified but where is that change needed

I dont believe OG images can render markdown so to counter this shortcoming we probably just want some static info which could be as simple as a tagline. We learned this lesson the hard way on our challenge og image but this has a couple benefits.

- deterministic layout(for the most part)
- no need to worry about NSFW content leaking onto the image

check out : https://og.typehero.dev/ for a quick glimpse of our images

**Comment by Dun-sin** [comment]
still confuses me a little, this issue focuses on rendering meta data for other sites right?
that means i should use the image in the OG url as the default and shouldn't be changed.
