### ISSUE TITLE
[Bug]: markdown renderer does not render details/summary tags

### ISSUE THREAD

**Issue by haze** [typehero/typehero#1033]
### What happened?

the problem area of https://typehero.dev/challenge/default-generic-arguments contains unrendered markdown at the bottom

### What browsers are you seeing the problem on?

All

**Comment by dimitropoulos** [comment]
good find.  The problem here is what it _should_ look like, to whoever picks this up (since, GitHub's markdown is functioning correctly)

<details>
<summary>small hint</summary>

Start with a literal object as the parameter default. Use [indexed types](https://typehero.dev/challenge/indexed-types).
 The error you'll see is because of a missing [generic constraint](https://typehero.dev/challenge/generic-type-constraints).

</details>
