### ISSUE TITLE
[Bug]: two slash often requires a reload of the editor to start working

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1181]
### What happened?

in the editor we support the two slash plugin `// ^?`

often times it doesnt work on initial use and requires a reload. code can be found in `twoslash.ts`

**Comment by me-imfhd** [comment]
how can i reproduce this ?

**Comment by bautistaaa** [comment]
> how can i reproduce this ?

add this to types in the user code 

<img width="1062" alt="CleanShot 2023-11-25 at 21 50 07@2x" src="https://github.com/typehero/typehero/assets/3660667/693149ee-1e3e-4960-863f-5b84fa5737b5">


you'll notice sometimes it doesnt load that gray overlay that shows the type

**Comment by me-imfhd** [comment]
my side, even that is not working, on reload

**Comment by DennisJosefsson** [comment]
I guess that's the issue here (that's an example, don't think I've seen it working anywhere so far), and it's quite confusing when the text assumes it's visible but it's not.
![slashslashtypeheroissue](https://github.com/typehero/typehero/assets/117932087/1572f861-de5e-4bbc-894c-b76af6fed739)

https://typehero.dev/challenge/indexed-types

**Comment by kfahad5607** [comment]
Tried to reproduce this issue, but the type is properly highlighted all the time.

Note: Make sure to align caret(^) with the variable name.

**Comment by bautistaaa** [comment]
i think this is a stale ticket
