### ISSUE TITLE
[Feature]: Mentions

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1478]
### Description

Users should be able to tag other users in comments and other applicable areas

related to: https://github.com/typehero/typehero/issues/1477

**Comment by dca123** [comment]
I am trying to understand why ? If there is a need outside of comments I understand (not sure where that is at tho), but wouldn't reply & comment notifications suffice here ? 

I imagine an interaction would go like this

- Solution posted by User A -> User B asks for a clarification as a comment -> User A makes a reply to that comment. 
- Solution posted by User A (he used awaited in the promise challenge) -> User B replies (bruh)

**Comment by dca123** [comment]
Since replies aren't treated as comment, but rather sub comments (I actually dig this implementation since a solution thread won't get bogged down with the conversation of two folks), I'm making an assumption that comments will be mutually exclusive of each other - are there any cases where someone might want to make a tag, but not make a reply ?
