### ISSUE TITLE
[Feature]: Add Badges/Flair to usernames

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1509]
### Description

Carrying the discussion over from https://github.com/typehero/typehero/issues/1496#issuecomment-2284717156

```
Badges:

Advent of Typescript 2023 (these exist now). we actually give 4 for the event. example here: https://typehero.dev/@satohshi
Advent of Typescript 2024
Maybe we only do badges for this event for now but that would make 8 if the accomplished 2024 Advent of Typescript

Flair:
Contributor
Subscriber
Admin/Moderator
more TBD
```

**Comment by dca123** [comment]
I think the best solution for this would be a hover card when on the usernames instead of showing it next to the usernames. This way, in the comments section, we could have flairs with badges to have context specific info such as 'Solution Author', 'Problem Author' or 'Community Educator'. These would be very specific flairs that would helpful when reading the discussions a solution. An example would be in PR's/issues in github where you can see a flair right by the comment. Let me know if you want me to detail my thought process here.

One solution is to roll in the contributor, sponsor, admin, hero, wizard as a badge. Sounds too ez and I'd rather have badges be what you earn via solving challenges.

Instead, these titles can be shown along side the badges on the hover card. Real estate is an issue here though, so I'd opt to show the latest/user highlighted badges, and the three latest/ user highlighted titles. Users with titles would be coloured so that it would hint users to hover over the username. 

Here's a figma prototype of the [comments section](https://www.figma.com/proto/p0WaY1Eq8QuD8hF7QML32F/TypeHero?page-id=6%3A288&node-id=6-291&viewport=689%2C561%2C0.65&t=QH2v8FWDTQnStBhp-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=6%3A291)

<img width="545" alt="image" src="https://github.com/user-attachments/assets/92306371-5540-43fa-b18a-c5919c2f4689">


Here is the [design page](https://www.figma.com/design/p0WaY1Eq8QuD8hF7QML32F/TypeHero?node-id=6-288&t=CSHV32osLPs0PXDY-1), I've some other variants of what the card looks like, I'll figure it out during implementation where i have a better feel for it as i code.

**Comment by bautistaaa** [comment]
> After my comments on #1496, I think the best solution for this would be a hover card on the usernames instead of showing it next to the usernames. This way, in the comments section, we could have flairs with badges to have context specific info such as 'Solution Author', 'Problem Author' or 'Community Educator'. These would be very specific flairs that would helpful when reading the discussions a solution. An example would be in PR's/issues in github where you can see a flair right by the comment. Let me know if you want me to detail my thought process here.
> 
> One solution is to roll in the contributor, sponsor, admin, hero, wizard as a badge. Sounds too ez and I'd rather have badges be what you earn via solving challenges.
> 
> Instead, these titles can be shown along side the badges on the hover card. Real estate is an issue here though, so I'd opt to show the latest/user highlighted badges, and the three latest/ user highlighted titles. Users with titles would be coloured so that it would hint users to hover over the username.
> 
> Here's a figma prototype of the [comments section](https://www.figma.com/proto/p0WaY1Eq8QuD8hF7QML32F/TypeHero?page-id=6%3A288&node-id=6-291&viewport=689%2C561%2C0.65&t=QH2v8FWDTQnStBhp-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=6%3A291)
> 
> <img alt="image" width="545" src="https://private-user-images.githubusercontent.com/3579142/357388079-92306371-5540-43fa-b18a-c5919c2f4689.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1ODM0NDIsIm5iZiI6MTcyMzU4MzE0MiwicGF0aCI6Ii8zNTc5MTQyLzM1NzM4ODA3OS05MjMwNjM3MS01NTQwLTQzZmEtYjE4YS1jNTkxOWMyZjQ2ODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMjEwNTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDFjNjE2NDE1NTA5OWQ3NWQ1YzEwYzVhMTZhYjcxNWIyOTE4NjZiOGMzNGNjYWNjZGU0ZGI1YjVkMGE3NmY1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BsVEyV9hgGhH4NH1J6rlzQe_CgT-hxS0SZjiYqPvYn4">
> Here is the [design page](https://www.figma.com/design/p0WaY1Eq8QuD8hF7QML32F/TypeHero?node-id=6-288&t=CSHV32osLPs0PXDY-1), I've some other variants of what the card looks like, I'll figure it out during implementation where i have a better feel for it as i code. Would value your inputs on what y'all find aesthetic and usable.

heck yeah! feel free to go nuts on the flair
