### ISSUE TITLE
[Bug]: Better error message on tracks page

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1571]
### What happened?

When not logged in and you visit a tracks page to enroll you get a generic error. It should at least tell you to log in to enroll or better maybe prompt them/redirect them to login and then do the action?

Showing a proper error message is fine for now though

### Relevant log output

```zsh
visit https://typehero.dev/tracks/typescript-foundations while not logged in.

click enroll
```

**Comment by aakash19here** [comment]
On local this returns correct message

**Comment by bautistaaa** [comment]
> On local this returns correct message 
> 
> 

check prod

**Comment by 17AnuragMishra** [comment]
Can I work on this!? Is it open for contribution

**Comment by bautistaaa** [comment]
> Can I work on this!? Is it open for contribution 

go for it

**Comment by 17AnuragMishra** [comment]
Thank you! Can you assign it to me so everyone knows I'm working on this?

**Comment by 17AnuragMishra** [comment]
I have already coded the stuff, but I'm really frustrated that I'm not able to run the file locally because I'm constantly getting this error, even though I have added the details correctly.
`web:dev:  ⨯ Error: No GITHUB_ID has been provided.
web:dev:     at eval (webpack-internal:///(rsc)/./src/server/auth.ts:12:11)
web:dev:     at (rsc)/./src/server/auth.ts (/home/anurag/typehero/apps/web/.next/server/app/page.js:1110:1)
web:dev:     at __webpack_require__ (/home/anurag/typehero/apps/web/.next/server/webpack-runtime.js:33:43)
web:dev:     at eval (webpack-internal:///(rsc)/./src/components/Navigation/index.tsx:22:71)
web:dev:     at (rsc)/./src/components/Navigation/index.tsx (/home/anurag/typehero/apps/web/.next/server/app/page.js:1318:1)
web:dev:     at __webpack_require__ (/home/anurag/typehero/apps/web/.next/server/webpack-runtime.js:33:43)
web:dev:     at eval (webpack-internal:///(rsc)/./src/app/layout.tsx:17:80)
web:dev:     at (rsc)/./src/app/layout.tsx (/home/anurag/typehero/apps/web/.next/server/app/page.js:407:1)
web:dev:     at Function.__webpack_require__ (/home/anurag/typehero/apps/web/.next/server/webpack-runtime.js:33:43)
web:dev:     at async e7 (/home/anurag/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:396747)
web:dev:     at async tS (/home/anurag/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:400444)
web:dev:     at async tw (/home/anurag/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:401005)
web:dev:     at async tO (/home/anurag/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:2130)
web:dev:     at async /home/anurag/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:2722 {
web:dev:   digest: '2716104956',
web:dev:   page: '/'
web:dev: }
web:dev:   4 |
web:dev:   5 | if (!process.env.GITHUB_ID) {
web:dev: > 6 |   throw new Error('No GITHUB_ID has been provided.');
web:dev:     |         ^
web:dev:   7 | }
web:dev:   8 |
web:dev:   9 | if (!process.env.GITHUB_SECRET) {
web:dev:  ○ Compiling /_error ...
`

**Comment by bautistaaa** [comment]
im assuming you have GITHUB_ID and GITHUB_SECRET in your .`env` and you see this during `pnpm dev`?

at any rate make a PR and it will deploy to a test env

**Comment by 17AnuragMishra** [comment]
Thank you, sir, for the information. I will simply do it.

**Comment by 17AnuragMishra** [comment]
@bautistaaa sir, ready with final changes, pls review it accordingly.

**Comment by 17AnuragMishra** [comment]
Thank you, sir, I couldn't reply or do the needful changes that was required, as I was preparing for my interview. Looking forward to doing more MEANINGFUL contributions.
