### ISSUE TITLE
[Bug]: Initially the solution is always marked incorrect

### ISSUE THREAD

**Issue by typesafeui** [typehero/typehero#1695]
### What happened?

When the challenge has been just opened, the solution is initially marked incorrect, so if you hit submit too fast the answer will be marked as incorrect
![image](https://github.com/user-attachments/assets/403ebc78-8583-403e-af94-b306a7f50369)

Steps to reproduce:
- Write a solution while logged out
- Login
- Go to the challenge and hit submit fast

Suggested solution:
Have a loading state when Monaco is loading all the needed types, and disable the submit button in that state

**Comment by nickbar01234** [comment]
Hey @typesafeui, not sure if you're still tracking this. I started to take a poke at the issue out of interests and wanted to bounce ideas. 

Just so we're on the same page, the problem is manifested in a race between submitting and `onMount` (the case you mentioned) / `onChange` for both the code and test editors - for example, I can add a new import statement and quickly submit the code to observe the same effect. Your suggested solution mentioned keeping a state for Monaco loading type which works, but I think it will have a weird UI effect, where certain code changes (like import) disable the button.

My high-level idea / proposal:
* We pass a counter as props to `SplitEditor` - this effectively serves as "active tasks".
* The counter increases when `onMount` or `onChange` is triggered and decreases when the method completes.
* When user submits, we inspect the counter. If the counter is positive, delay the submission.
