### ISSUE TITLE
[Feature]: Settings Modal Needs Some Love

### ISSUE THREAD

**Issue by ggrandi** [typehero/typehero#519]
### Description

If someone who is good at design wants to fix the [`/apps/web/src/app/challenge/_components/settings/settings-form.tsx`](https://github.com/bautistaaa/typehero/tree/main/apps/web/src/app/challenge/_components/settings/settings-form.tsx) file, I recently added a vim config textarea but I had no clue how to style it in a way that doesn't suck

(this is what it currently looks like):
<img width="1552" alt="image" src="https://github.com/bautistaaa/typehero/assets/49359646/4563d496-4166-4cf6-af01-3b460c673c5e">

**Comment by Tylopilus** [comment]
mh I noticed the following things:
* does it make sense to show the vim-config at all if the user has selected standard keybindings?
* Keyboard-Shortcuts modal displays only shortcuts that apply for standard keybindings

Should we maybe switch the keyboards-shortcuts modal to show the vimconfig if the user has selected vim-keybinding and then display on the screenshot above just a `configure keybindings` link instead of the textbox?

**Comment by kualta** [comment]
> Should we maybe switch the keyboards-shortcuts modal to show the vimconfig if the user has selected vim-keybinding and then display on the screenshot above just a configure keybindings link instead of the textbox?

I agree, unify vim and normal keybinds under one modal and change it depending on the current user configuration seems like the way to go

**Comment by kualta** [comment]
I can take this one if no one else wants it
