### ISSUE TITLE
[Feature]: cookie consent banner

### ISSUE THREAD

**Issue by Hacksore** [typehero/typehero#777]
### Description

make goodlookin™ based on design from @PickleNik if he can otherwise use mine.

but for just just a banner and use `localStorge` to set if they've seen it or not.

![image](https://github.com/typehero/typehero/assets/996134/c673cd97-d8f1-49be-ba8e-6a07b6a63563)

**Comment by G-R3** [comment]
can I hack away at this?

**Comment by Hacksore** [comment]
@G-R3 :shipit:

**Comment by G-R3** [comment]
hey @Hacksore what would you like the text content to say? Also does it make sense to just have one button instead of the two? maybe just have it say `Understand` or something 😅. I did some work on this and this what I have so far.

https://github.com/typehero/typehero/assets/48399420/af9737d8-4a71-4213-80d3-d13dfadcac0e

<img width="1511" alt="Screenshot 2023-10-06 at 12 15 14 AM" src="https://github.com/typehero/typehero/assets/48399420/0dc4fc47-d148-4277-b891-c894d303ec25">
<img width="1509" alt="Screenshot 2023-10-06 at 12 15 02 AM" src="https://github.com/typehero/typehero/assets/48399420/57d64705-ca1f-4623-89d2-0ba826fed85d">
<img width="354" alt="Screenshot 2023-10-06 at 12 14 47 AM" src="https://github.com/typehero/typehero/assets/48399420/a755100d-6dac-4baf-a4de-23736c67ad0b">
<img width="355" alt="Screenshot 2023-10-06 at 12 14 06 AM" src="https://github.com/typehero/typehero/assets/48399420/bae35682-53bb-4948-a98b-419780d27bb6">
