### ISSUE TITLE
[Feature]: move tanstack query devtools logo somewhere not annoying on the screen

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#794]
### Description

![image](https://github.com/typehero/typehero/assets/3660667/e96fda40-3a41-4106-879a-4e9fc0363398)

**Comment by bautistaaa** [comment]
or even configurable locally

**Comment by vivekKumarSinghH** [comment]
@bautistaaa  please assign this to me

**Comment by vivekKumarSinghH** [comment]
> @bautistaaa please assign this to me
Currently, there are only four possible corner positions for the logo. Where should I place it, and what does "locally configurable" mean?
![image](https://github.com/typehero/typehero/assets/72158561/c1cd9d0f-f77b-413b-9ce1-5df0d281c620)

**Comment by Hacksore** [comment]
Going to reopen this cause it does go over the login button.
<img width="217" alt="image" src="https://github.com/typehero/typehero/assets/996134/0603cbaa-e33c-4af9-8b50-63738e19dcea">

Maybe we can programmatically invoke it so that even if it's in a bad spot like bottom right you only open it when you need it.

**Comment by odicho** [comment]
I've played around a little and it seems like bottom-right with some additional bottom padding to move it up a little is the best spot for it. What do you think??

![Screenshot 2023-10-18 at 9 28 32 PM](https://github.com/typehero/typehero/assets/53154523/0289955c-f906-4825-a9df-d7d32ba287db)
